version: '3'

services:
  jenkins:
    container_name: jenkins
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    networks:
      - sonarnet
    restart: always
    privileged: true
    volumes:
      - jenkins_home:/var/jenkins_home
      - docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - sonarnet
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
     - SONARQUBE_JDBC_USERNAME=sonar
     - SONARQUBE_JDBC_PASSWORD=sonar    

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar 
    networks:
      - sonarnet
    sysctls:
      - net.core.somaxconn=1024
      - vm.max_map_count=262144
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    
    
volumes:
  jenkins_home:
  docker.sock:

networks:
  sonarnet:
    driver: bridge











